const dotenv = require('dotenv');
dotenv.config();

const INFURA_CREDENTAILS = {
    INFURA_URL: process.env.INFURA_URL,
    INFURA_KEY: process.env.INFURA_KEY
}

const DATABASE_CREDENTIALS = {
    MONGODB_URL: process.env.MONGODB_URL
}

const ETHERSCAN_CREDENTIALS = {
    ETHERSCAN_API_KEY: process.env.ETHERSCAN_API_KEY,
    ETHERSCAN_URL: process.env.ETHERSCAN_URL
}

const APEX_NFT_CONTRACT_ADDRESS = process.env.APEX_NFT_CONTRACT_ADDRESS;

const PINATA_CREDENTIALS = {
    PINATA_API_KEY: process.env.PINATA_API_KEY,
    PINATA_SECRET_API_KEY: process.env.PINATA_API_SECRET_KEY,
    PINATA_JWT_TOKEN: process.env.PINATA_JWT_TOKEN,
    PINATA_GATEWAY_URL: process.env.PINATA_GATEWAY_URL,
    PINATA_GATEWAY_KEY: process.env.PINATA_GATEWAY_KEY
}

const ERC20_CONTRACT_ADDRESS = process.env.ERC20_ADDRESS;
const WITHDRAW_WALLET_PRIVATE_KEY = process.env.WITHDRAW_WALLET_PRIVATE_KEY;

module.exports = {
    INFURA_CREDENTAILS,
    DATABASE_CREDENTIALS,
    ETHERSCAN_CREDENTIALS,
    APEX_NFT_CONTRACT_ADDRESS,
    PINATA_CREDENTIALS,
    ERC20_CONTRACT_ADDRESS,
    WITHDRAW_WALLET_PRIVATE_KEY
}